"""adding program and service tables

Revision ID: 0407f93e70af
Revises: a6f8ba5881e2
Create Date: 2020-01-20 20:40:24.106041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0407f93e70af'
down_revision = 'a6f8ba5881e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables if they exist
    op.drop_table('service')
    op.drop_table('program_service_type')
    op.drop_table('service_type')
    op.drop_table('program')

    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('begin_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_created_date'), 'service', ['created_date'], unique=False)
    op.create_index(op.f('ix_client_address_created_date'), 'client_address', ['created_date'], unique=False)
    op.create_index(op.f('ix_client_contact_created_date'), 'client_contact', ['created_date'], unique=False)
    op.create_index(op.f('ix_client_race_created_date'), 'client_race', ['created_date'], unique=False)
    op.create_index(op.f('ix_client_relationship_created_date'), 'client_relationship', ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_relationship_created_date'), table_name='client_relationship')
    op.drop_index(op.f('ix_client_race_created_date'), table_name='client_race')
    op.drop_index(op.f('ix_client_contact_created_date'), table_name='client_contact')
    op.drop_index(op.f('ix_client_address_created_date'), table_name='client_address')
    op.drop_index(op.f('ix_service_created_date'), table_name='service')
    op.drop_table('service')
    op.drop_table('program_service_type')
    op.drop_table('service_type')
    op.drop_table('program')
    # ### end Alembic commands ###
