"""OM tables

Revision ID: 3654c268fc5e
Revises: 0e29b59348fd
Create Date: 2020-01-28 11:10:29.722438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3654c268fc5e'
down_revision = '0e29b59348fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assess_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assess_type_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assess_type_id'], ['assessment_type.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome_matrix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('housing', sa.Integer(), nullable=True),
    sa.Column('transportation', sa.Integer(), nullable=True),
    sa.Column('employment', sa.Integer(), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('childcare', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('housing_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['housing_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('housing_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length = 20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('outcome_domain_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length = 20), nullable=True),
    sa.Column('score', sa.Integer, nullable=True),
    sa.Column('score_description', sa.String(length = 50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome_matrix')
    op.drop_table('assessment')
    op.drop_table('assessment_type')
    op.drop_table('housing_assessment')
    op.drop_table('housing_status')
    op.drop_table('outcome_domain_levels')
    # ### end Alembic commands ###
