"""empty message

Revision ID: 4ab97d8b9c0b
Revises: e6f1de1cb365
Create Date: 2019-12-17 13:52:12.475706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab97d8b9c0b'
down_revision = 'e6f1de1cb365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ethnicity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ethnicity', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('middle_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('SSN', sa.String(length=11), nullable=True),
    sa.Column('veteran', sa.Boolean(), nullable=True),
    sa.Column('activeMilitary', sa.Boolean(), nullable=True),
    sa.Column('disability', sa.Boolean(), nullable=True),
    sa.Column('foreignBorn', sa.Boolean(), nullable=True),
    sa.Column('ethnicity', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ethnicity'], ['ethnicity.id'], ),
    sa.ForeignKeyConstraint(['gender'], ['gender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('contact_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['contact_type'], ['contact_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_a_id', sa.Integer(), nullable=True),
    sa.Column('client_b_id', sa.Integer(), nullable=True),
    sa.Column('a_to_b_relation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['a_to_b_relation'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['client_a_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_b_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_relationship')
    op.drop_table('client_race')
    op.drop_table('client_contact')
    op.drop_table('client_address')
    op.drop_table('client')
    op.drop_table('relationship')
    op.drop_table('race')
    op.drop_table('gender')
    op.drop_table('ethnicity')
    op.drop_table('contact_type')
    # ### end Alembic commands ###
