"""empty message

Revision ID: 53228e8b5ecc
Revises: 0407f93e70af
Create Date: 2020-01-25 20:17:41.478071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53228e8b5ecc'
down_revision = '0407f93e70af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('middle_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('SSN', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiosk_timestamp'), 'kiosk', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kiosk_timestamp'), table_name='kiosk')
    op.drop_table('kiosk')
    # ### end Alembic commands ###
