"""empty message

Revision ID: 6080b925ed30
Revises: f32584a8d802
Create Date: 2020-01-20 14:21:46.978804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6080b925ed30'
down_revision = 'f32584a8d802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop and recreate client table
    op.drop_table('client')
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('middle_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('SSN', sa.String(length=11), nullable=True),
    sa.Column('veteran', sa.Boolean(), nullable=True),
    sa.Column('activeMilitary', sa.Boolean(), nullable=True),
    sa.Column('disability', sa.Boolean(), nullable=True),
    sa.Column('foreignBorn', sa.Boolean(), nullable=True),
    sa.Column('ethnicity', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ethnicity'], ['ethnicity.id'], ),
    sa.ForeignKeyConstraint(['gender'], ['gender.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Drop and recreate client_relationship table
    op.drop_table('client_relationship')
    op.create_table('client_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_a_id', sa.Integer(), nullable=True),
    sa.Column('client_b_id', sa.Integer(), nullable=True),
    sa.Column('a_to_b_relation', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['a_to_b_relation'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['client_a_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_b_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('middle_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('SSN', sa.String(length=11), nullable=True),
    sa.Column('veteran', sa.Boolean(), nullable=True),
    sa.Column('activeMilitary', sa.Boolean(), nullable=True),
    sa.Column('disability', sa.Boolean(), nullable=True),
    sa.Column('foreignBorn', sa.Boolean(), nullable=True),
    sa.Column('ethnicity', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ethnicity'], ['ethnicity.id'], ),
    sa.ForeignKeyConstraint(['gender'], ['gender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('client_relationship')
    op.create_table('client_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_a_id', sa.Integer(), nullable=True),
    sa.Column('client_b_id', sa.Integer(), nullable=True),
    sa.Column('a_to_b_relation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['a_to_b_relation'], ['relationship.id'], ),
    sa.ForeignKeyConstraint(['client_a_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['client_b_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###
