"""empty message

Revision ID: f32584a8d802
Revises: 4ab97d8b9c0b
Create Date: 2020-01-19 11:06:10.411880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32584a8d802'
down_revision = '4ab97d8b9c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'dob')
    # ### end Alembic commands ###
